# Generated by Django 4.2.16 on 2024-10-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_on_college',
            options={'verbose_name': 'Add On College'},
        ),
        migrations.AlterModelOptions(
            name='add_on_programme',
            options={'verbose_name': 'Add on Programme'},
        ),
        migrations.AlterModelOptions(
            name='add_on_programme_college_affiliation_bangalore',
            options={'verbose_name': 'Add On Programme College Affiliation Bangalore'},
        ),
        migrations.AlterModelOptions(
            name='add_on_programme_college_affiliation_kerla',
            options={'verbose_name': 'Add On Programme College Affiliation Kerla'},
        ),
        migrations.AlterModelOptions(
            name='admission_registration',
            options={'verbose_name': 'Admission Registration'},
        ),
        migrations.AlterModelOptions(
            name='affiliated_vocational_training_college_kerla',
            options={'verbose_name': 'Affiliated Vocational Training College Kerla'},
        ),
        migrations.AlterModelOptions(
            name='amount_status',
            options={'verbose_name': 'Amount Status'},
        ),
        migrations.AlterModelOptions(
            name='application_for_affliation',
            options={'verbose_name': 'Application for Affliation'},
        ),
        migrations.AlterModelOptions(
            name='certificate_course',
            options={'verbose_name': 'Certificate Course'},
        ),
        migrations.AlterModelOptions(
            name='college_name',
            options={'verbose_name': 'College Name'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='course_name',
            options={'verbose_name': 'Course Name'},
        ),
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'Custome User'},
        ),
        migrations.AlterModelOptions(
            name='diploma_programme',
            options={'verbose_name': 'Diploma Programme'},
        ),
        migrations.AlterModelOptions(
            name='e_employee_daily_work_statement',
            options={'verbose_name': 'E Employee Daily Work Statement'},
        ),
        migrations.AlterModelOptions(
            name='e_employee_leave_status',
            options={'verbose_name': 'E Employee Leave Status'},
        ),
        migrations.AlterModelOptions(
            name='e_employee_live_status',
            options={'verbose_name': 'E Employee Live Status'},
        ),
        migrations.AlterModelOptions(
            name='e_employee_record',
            options={'verbose_name': 'E Employee Record'},
        ),
        migrations.AlterModelOptions(
            name='e_office_account',
            options={'verbose_name': 'E Office Account'},
        ),
        migrations.AlterModelOptions(
            name='e_office_file_sanction',
            options={'verbose_name': 'E Office File Sanction'},
        ),
        migrations.AlterModelOptions(
            name='e_office_queue',
            options={'verbose_name': 'E Office Queue'},
        ),
        migrations.AlterModelOptions(
            name='employee_live_and_leave_status',
            options={'verbose_name': 'Employee Live And Leave Status'},
        ),
        migrations.AlterModelOptions(
            name='employee_record_type',
            options={'verbose_name': 'Employee Record Type'},
        ),
        migrations.AlterModelOptions(
            name='employee_status',
            options={'verbose_name': 'Employee Status'},
        ),
        migrations.AlterModelOptions(
            name='exam_fees_type',
            options={'verbose_name': 'Exam Fees Type'},
        ),
        migrations.AlterModelOptions(
            name='exam_registration',
            options={'verbose_name': 'Exam Registration'},
        ),
        migrations.AlterModelOptions(
            name='fee_type',
            options={'verbose_name': 'Fee Type'},
        ),
        migrations.AlterModelOptions(
            name='free_skill_training',
            options={'verbose_name': 'Free Skill Training'},
        ),
        migrations.AlterModelOptions(
            name='institution_status',
            options={'verbose_name': 'Institution Status'},
        ),
        migrations.AlterModelOptions(
            name='main_course',
            options={'verbose_name': 'Main Course'},
        ),
        migrations.AlterModelOptions(
            name='mark_list_registration',
            options={'verbose_name': 'Mark List Registration'},
        ),
        migrations.AlterModelOptions(
            name='mark_status',
            options={'verbose_name': 'Mark Status'},
        ),
        migrations.AlterModelOptions(
            name='nature_of_leave',
            options={'verbose_name': 'Nature of Leave'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AlterModelOptions(
            name='particulars_head',
            options={'verbose_name': 'Particulars Head'},
        ),
        migrations.AlterModelOptions(
            name='pay_online_fees',
            options={'verbose_name': 'Pay Online Fees'},
        ),
        migrations.AlterModelOptions(
            name='pg_diploma_programme',
            options={'verbose_name': 'PG Diploma Programme'},
        ),
        migrations.AlterModelOptions(
            name='result_status',
            options={'verbose_name': 'Result Status'},
        ),
        migrations.AlterModelOptions(
            name='staff_work_allotment',
            options={'verbose_name': 'Staff Work Allotment'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='type_of_account',
            options={'verbose_name': 'Type of Account'},
        ),
        migrations.AlterModelOptions(
            name='user_role',
            options={'verbose_name': 'User Role'},
        ),
        migrations.AlterModelOptions(
            name='visitor_ip',
            options={'verbose_name': 'Visitor IP'},
        ),
        migrations.AlterModelOptions(
            name='vocational_course',
            options={'verbose_name': 'Vocational Course'},
        ),
        migrations.AlterModelOptions(
            name='vtc_course_admission_registration',
            options={'verbose_name': 'VTC Course Admission Registration'},
        ),
        migrations.AlterModelOptions(
            name='work_assign_office',
            options={'verbose_name': 'Work Assign Office'},
        ),
        migrations.AlterModelOptions(
            name='work_status',
            options={'verbose_name': 'Work Status'},
        ),
    ]
