# Generated by Django 4.2.16 on 2024-10-24 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("nationalyouth", "0002_alter_add_on_college_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=200, null=True, unique=True)),
                ("meta_title", models.CharField(blank=True, max_length=70, null=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "meta_keywords",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "blog_image",
                    models.ImageField(upload_to="image/download/uploads/blog_image/"),
                ),
            ],
        ),
    ]
