# Generated by Django 4.2.16 on 2024-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nationalyouth", "0003_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=250)),
            ],
        ),
    ]
