# Generated by Django 4.2.16 on 2024-12-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0007_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_for_affliation',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application_for_affliation',
            name='manager_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_for_affliation',
            name='manager_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application_for_affliation',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application_for_affliation',
            name='principal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_for_affliation',
            name='principal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
