# Generated by Django 4.2.16 on 2024-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0008_application_for_affliation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_for_affliation',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
