# Generated by Django 4.2.16 on 2025-01-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0011_alter_mark_list_registration_external_marks_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_director_approval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_director_remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_director_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrate_director_status', to='nationalyouth.status'),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_officer_approval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_officer_approval_remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='administrate_officer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrate_officer_status', to='nationalyouth.status'),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='officer_approval_remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='officer_approval_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_approval_status', to='nationalyouth.status'),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='staff_approval_remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='e_office_account',
            name='staff_approval_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_approval_status', to='nationalyouth.status'),
        ),
        migrations.AlterField(
            model_name='e_office_account',
            name='remark_officer_approval',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_office_account',
            name='remark_staff_approval',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
