# Generated by Django 4.2.16 on 2025-01-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0012_e_office_account_administrate_director_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_office_account',
            old_name='officer_approval_remarks',
            new_name='officer_approval',
        ),
        migrations.RenameField(
            model_name='e_office_account',
            old_name='staff_approval_remarks',
            new_name='staff_approval',
        ),
    ]
