# Generated by Django 4.2.16 on 2025-01-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0013_rename_officer_approval_remarks_e_office_account_officer_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_employee_record',
            name='head_office',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='e_employee_record',
            name='pf_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='E_Employee_Record_Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=25, null=True)),
                ('year', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.CharField(blank=True, max_length=25, null=True)),
                ('clerk', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved')], max_length=250)),
                ('fo', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved')], max_length=250)),
                ('executive_officer', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved')], max_length=250)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nationalyouth.e_employee_record')),
            ],
        ),
    ]
