# Generated by Django 4.2.16 on 2025-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0014_e_employee_record_head_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_for_affliation',
            name='type',
            field=models.CharField(blank=True, choices=[('addon', 'addon'), ('vtc', 'vtc')], default='vtc', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mark_list_registration',
            name='result',
            field=models.CharField(blank=True, choices=[('pass', 'Passed'), ('fail', 'Failed')], max_length=25, null=True),
        ),
    ]
