# Generated by Django 4.2.16 on 2025-01-22 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0015_application_for_affliation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_vocational_training_college_kerla',
            name='fee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='affiliated_vocational_training_college_kerla',
            name='from_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='affiliated_vocational_training_college_kerla',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nationalyouth.status'),
        ),
        migrations.AddField(
            model_name='affiliated_vocational_training_college_kerla',
            name='to_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
