# Generated by Django 4.2.16 on 2025-01-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalyouth', '0016_affiliated_vocational_training_college_kerla_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_office_account',
            name='office_referral_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_office_account',
            name='officer_incharge_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='e_office_account',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
